import { Body, Controller, Get, Param, Patch, Post, Put, Query, UseGuards } from '@nestjs/common';
import { RequireModule } from '../../common/decorators/metadata.decorator';
import { TenantCtx, User } from '../../common/decorators/params.decorator';
import type { AuthUser, TenantContext } from '../../common/decorators/params.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { TenantGuard } from '../../common/guards/tenant.guard';
import { ModuleEnabledGuard } from '../../common/guards/module-enabled.guard';
import { SmartPublishingService } from './smart-publishing.service';
@Controller('publishing') @UseGuards(JwtAuthGuard, TenantGuard, ModuleEnabledGuard) @RequireModule('smart-publishing')
export class SmartPublishingController { constructor(private service: SmartPublishingService) {} @Get('settings') settings(@TenantCtx() t:TenantContext){return this.service.getSettings(t.tenantId)} @Put('settings') saveSettings(@TenantCtx() t:TenantContext,@Body() b:any){return this.service.setSettings(t.tenantId,b)} @Get('channels') channels(@TenantCtx() t: TenantContext) { return this.service.channels(t.tenantId); } @Post('channels') createChannel(@TenantCtx() t: TenantContext, @Body() b: any) { return this.service.createChannel(t.tenantId, b); } @Get('articles') articles(@TenantCtx() t: TenantContext, @Query('status') s?: string) { return this.service.articles(t.tenantId, s); } @Post('articles') createArticle(@TenantCtx() t: TenantContext, @User() u: AuthUser, @Body() b: any) { return this.service.createArticle(t.tenantId, u.id, b); } @Post('articles/:id/publish') publish(@TenantCtx() t: TenantContext, @Param('id') id: string) { return this.service.publish(t.tenantId, id); } @Get('news/feeds') newsFeeds(@TenantCtx() t:TenantContext){return this.service.newsFeeds(t.tenantId)} @Post('news/feeds') addNewsFeed(@TenantCtx() t:TenantContext,@Body() b:any){return this.service.addNewsFeed(t.tenantId,b)} @Post('news/feeds/:id/fetch') fetchNews(@TenantCtx() t:TenantContext,@Param('id') id:string){return this.service.fetchNewsFeed(t.tenantId,id)} @Get('news/articles') newsArticles(@TenantCtx() t:TenantContext,@Query('status') s?:string){return this.service.newsArticles(t.tenantId,s)} @Post('news/articles/:id/summarize') summarize(@TenantCtx() t:TenantContext,@Param('id') id:string){return this.service.summarizeNews(t.tenantId,id)} @Post('news/articles/:id/reject') reject(@TenantCtx() t:TenantContext,@Param('id') id:string){return this.service.rejectNews(t.tenantId,id)} @Patch('news/articles/:id') updateNews(@TenantCtx() t:TenantContext,@Param('id') id:string,@Body() b:any){return this.service.updateNewsArticle(t.tenantId,id,b)} @Get('social/feeds') socialFeeds(@TenantCtx() t:TenantContext){return this.service.socialFeeds(t.tenantId)} @Post('social/feeds') addSocialFeed(@TenantCtx() t:TenantContext,@Body() b:any){return this.service.addSocialFeed(t.tenantId,b)} @Get('social/articles') socialArticles(@TenantCtx() t:TenantContext,@Query('status') s?:string){return this.service.socialArticles(t.tenantId,s)} @Patch('social/articles/:id/rewrite') rewrite(@TenantCtx() t:TenantContext,@Param('id') id:string,@Body() b:any){return this.service.rewriteSocialArticle(t.tenantId,id,b.rewrittenText)} }
