packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "bcrypt"
  - "prisma"
  - "sharp"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
