'use client';
import { Users, UserCheck, Calendar, LayoutDashboard } from 'lucide-react';
import { ProtectedLayout } from '@/components/layout/protected-layout';
import { Card, CardContent } from '@/components/ui/card';
import { useApi } from '@/hooks/use-api';
import { formatJalaliDateTime } from '@/lib/date';
import { formatPersianDigits } from '@deska/shared';
interface DashboardStats { contacts: number; employees: { active: number }; core: { upcomingEvents: number }; generatedAt: string; }
function DashboardContent() { const { data, isLoading, error } = useApi<DashboardStats>('/dashboard/stats'); if (isLoading) return <div className="flex justify-center py-24"><div className="h-10 w-10 animate-spin rounded-full border-4 border-primary-600 border-t-transparent" /></div>; if (error) return <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-red-700">{error}</div>; if (!data) return null; const stats = [{ t: 'مخاطبین', v: data.contacts, i: Users, tone: 'bg-blue-50 text-blue-700' }, { t: 'کارمندان فعال', v: data.employees.active, i: UserCheck, tone: 'bg-violet-50 text-violet-700' }, { t: 'رویدادهای پیش رو', v: data.core.upcomingEvents, i: Calendar, tone: 'bg-amber-50 text-amber-700' }]; return <div className="mx-auto w-full max-w-7xl space-y-6" dir="rtl"><header className="flex items-start gap-4 rounded-3xl bg-gradient-to-l from-slate-950 via-slate-900 to-blue-950 p-6 text-white shadow-xl shadow-slate-900/10"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10 ring-1 ring-white/15"><LayoutDashboard className="h-6 w-6" /></span><div><h2 className="text-2xl font-bold">داشبورد</h2><p className="mt-2 text-sm text-slate-300">نمای کلی وضعیت سازمان و آخرین فعالیت‌ها</p><p className="mt-1 text-xs text-slate-400">آخرین بروزرسانی: {formatJalaliDateTime(data.generatedAt)}</p></div></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{stats.map(({ t, v, i: Icon, tone }) => <Card key={t} className="transition hover:-translate-y-0.5 hover:shadow-md"><CardContent className="flex items-center gap-4 p-6"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-6 w-6" /></span><div><p className="text-sm text-slate-500">{t}</p><p className="mt-1 text-2xl font-bold text-slate-900">{formatPersianDigits(v)}</p></div></CardContent></Card>)}</div></div>; }
export default function DashboardPage() { return <ProtectedLayout title="داشبورد"><DashboardContent /></ProtectedLayout>; }
