'use client';

import Link from 'next/link';
import { Bot, FileText, Plus, Rss, Share2 } from 'lucide-react';
import { ProtectedLayout } from '@/components/layout/protected-layout';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useApi } from '@/hooks/use-api';

export default function SocialPage() {
  const feeds = useApi<any[]>('/publishing/feeds');
  const articles = useApi<any[]>('/publishing/social/articles');
  const sources = Array.isArray(feeds.data) ? feeds.data.filter((feed) => feed.purpose === 'social-studio') : [];
  const rows = Array.isArray(articles.data) ? articles.data : [];
  return <ProtectedLayout title="استودیوی اجتماعی"><main className="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6" dir="rtl">
    <header className="flex flex-col gap-5 rounded-3xl bg-gradient-to-l from-slate-950 via-slate-900 to-violet-950 p-6 text-white shadow-xl shadow-slate-900/10 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10 ring-1 ring-white/15"><Share2 className="h-6 w-6" /></span><div><h1 className="text-2xl font-bold">استودیوی اجتماعی</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">محتوای مناسب شبکه‌های اجتماعی را از منابع منتخب دریافت و برای انتشار آماده کنید.</p></div></div><Link href="/publishing/feeds" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-900 hover:bg-slate-100"><Plus className="h-4 w-4" /> مدیریت فیدها</Link></header>
    <section className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><div className="text-2xl font-bold text-violet-700">{sources.length}</div><div className="mt-1 text-sm text-slate-500">فید فعال استودیوی اجتماعی</div></Card><Card className="p-4"><div className="text-2xl font-bold text-slate-900">{rows.length}</div><div className="mt-1 text-sm text-slate-500">محتوای دریافت‌شده</div></Card><Card className="p-4"><div className="text-2xl font-bold text-emerald-700">{rows.filter((row) => row.status === 'ready').length}</div><div className="mt-1 text-sm text-slate-500">آماده انتشار</div></Card></section>
    <section className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">منابع استودیوی اجتماعی</h2><p className="mt-1 text-sm text-slate-500">فقط فیدهای دارای کاربرد استودیوی اجتماعی نمایش داده می‌شوند.</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">{sources.length} فید</span></div>{sources.length === 0 ? <div className="mt-5 flex items-center gap-3 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500"><Rss className="h-5 w-5" /> هنوز فیدی برای این بخش انتخاب نشده است.</div> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{sources.map((feed) => <div className="rounded-2xl border border-slate-200 p-4 transition hover:border-violet-300 hover:bg-violet-50/30" key={feed.id}><div className="font-semibold text-slate-900">{feed.name}</div><div className="mt-2 truncate text-xs text-slate-500" dir="ltr">{feed.url}</div></div>)}</div>}</Card><Card className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Bot className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-900">آماده‌سازی محتوا</h2><p className="mt-1 text-xs text-slate-500">این بخش در مرحلهٔ بعدی توسعه فعال می‌شود.</p></div></div><div className="mt-5 rounded-2xl border border-dashed border-violet-200 bg-violet-50/50 p-5 text-sm leading-7 text-violet-800">منابع را از صفحهٔ فیدها مشخص کنید؛ فرایند بازنویسی و انتشار اجتماعی پس از تکمیل سناریوی این بخش فعال خواهد شد.</div><Button className="mt-3 w-full" variant="outline" disabled><FileText className="h-4 w-4" /> به‌زودی</Button></Card></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold text-slate-900">محتواهای اجتماعی</h2><span className="text-sm text-slate-500">{rows.length} مورد</span></div>{rows.length === 0 ? <Card className="flex min-h-48 flex-col items-center justify-center p-8 text-center"><Share2 className="h-8 w-8 text-slate-300" /><p className="mt-3 text-sm text-slate-500">هنوز محتوای اجتماعی دریافت نشده است.</p></Card> : <div className="grid gap-4 md:grid-cols-2">{rows.map((row) => <Card className="p-5 transition hover:-translate-y-0.5 hover:shadow-md" key={row.id}><div className="flex items-start justify-between gap-3"><h3 className="font-bold leading-7 text-slate-900">{row.title || 'بدون عنوان'}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{row.status}</span></div><p className="mt-3 line-clamp-4 text-sm leading-7 text-slate-600">{row.rewrittenText || row.summaryText || row.originalText || 'بدون متن'}</p></Card>)}</div>}</section>
  </main></ProtectedLayout>;
}
